### ISSUE TITLE
我需要做一个拖拽排序的功能(列表A,B,C,D,)， 假设A拖拽到D的后面，我能拿到D这个元素(对象)么？

### ISSUE THREAD

**Issue by WiFiUncle** [Barrior/DDSort#10]
`
<li id=A>AAA</li>
<li id=B>BBB</li>
<li id=C>CCC</li>
<li id=D>DDD</li>
`
我的需求是这样的，我需要做一个拖拽功能，并且把拖拽后的新结果告诉后台。 
举个例子，我现在拖拽B到D的后面，B元素的id是能拿到，但是我怎么知道我是拖到D的后面呢？(也可能是A的前面)  ，有办法获取么？
感谢！

**Comment by WiFiUncle** [comment]
`
//向上排序
`if( prev.length && top < prev.offset().top + prev.outerHeight()/2 ){
			clone.after( prev );
                        console.log("--------prev-------");
						console.log(prev);
                        console.log("--------prev-------");
						
					//向下排序
					}else if( next.length && top + thisOuterHeight > next.offset().top + next.outerHeight()/2 ){
						
						clone.before( next );
                        console.log("--------next-------");
                        console.log(next);
                        console.log("--------next-------");

					}`
//应该是找到了。我试试。。。`

**Comment by lupingxing** [comment]
说一下思路：鼠标松开时找到当前元素的前一个元素就可以了

**Comment by Barrior** [comment]
@WiFiUncle ， @lupingxing 正解啊，都是对 DOM 操作，up 钩子函数里找到这个元素的上一个元素就可以了

**Comment by WiFiUncle** [comment]
这个问题已经处理了。方法如上。
现在正在解决另外一个问题，假设用户拖拽后，又放回远处，我就不用向后台发送排序请求了。
我的思路是:
     先在按下鼠标  down方法中记住index， 再在松开鼠标 up方法中，先获取当前列表的dom (我是用在tabel中用，获取到tr 的listArr数组) ，再用listArr[index] 和当前的选中的对象对比，一致则不发送。

**Comment by WiFiUncle** [comment]
霍霍。完美解决~~~
(不过dom对象直接比较不会相等，我在里面都取了序号作比较的。)

**Comment by Barrior** [comment]
那就关闭了
