### ISSUE TITLE
屏幕滚动条下拉到底部时，会出现拖拽块位置偏移

### ISSUE THREAD

**Issue by twt898xu** [Barrior/DDSort#11]
如图片所示，鼠标位置在当前红圈处，当左侧滚动条下拉到底部时，拖拽块会与鼠标便宜较大距离![qq 20171030095007](https://user-images.githubusercontent.com/28769187/32151497-61458084-bd58-11e7-85e0-86ec22a9663b.png)
望解决

**Comment by Barrior** [comment]
@mcxu233 你这个是 `demo_bootstrap.html` 演示出来的效果吗，我这边看不到这样的 `BUG`，方便的话，你给一个在线的出错示例？

**Comment by twt898xu** [comment]
@Barrior 我用你的`demo_bootstarp.html`录制了`gif`你看看。具体现象就是当滚动条拉到底部时，会出现拖拽块与鼠标位置偏移过大。
![demo](https://user-images.githubusercontent.com/28769187/32529001-e6129cd8-c470-11e7-892b-a70e544ccb11.gif)

**Comment by Barrior** [comment]
@mcxu233 
有滚动条的时候是有这个问题，谢谢提交这个问题。
已经提交代码，完善在 `bootstrap modal` 中的使用方案，在 `move` 函数里加上去顶部距离的代码 `$(this).css('top', top - $('.modal-dialog').offset().top)` 就可以了。
