### ISSUE TITLE
function update or destroy?

### ISSUE THREAD

**Issue by my-instantcms** [Barrior/DDSort#17]
Hello.
Thanks for the script.
Is there a function to update or destroy?
I add a new block for ajax and the script does not see it.
I tried to announce the script again after the ajax, but then everything breaks down.
There is a lack of a function to update or destroy, so that after the Ajax you can call again

**Comment by Barrior** [comment]
Hi.
Thanks for your use.
Excuse my understanding is not very clear.
You could resolve the problem with either of the two ways below.
1. Your can tigger again the method (`$('.wrapper').DDSort(...)`) after the new block was rendered on the DOM tree.
1. You can set a higher level delegate element maybe ( like this`$('.parent-element').DDSort(...)`).
