### ISSUE TITLE
拖动的时候元素可以保持原来的样式不变吗？表格拖动会变形

### ISSUE THREAD

**Issue by Maxatom** [Barrior/DDSort#18]

**Comment by Barrior** [comment]
@Maxatom 可以考虑下变形的原因，拖动的时候会克隆一个同的元素做为占位符，而拖动的元素是固定定位的，理解上貌似不会影响原来的表格。

**Comment by Maxatom** [comment]
@Barrior 
拖动后不会，正在推动的行变短了，内容少的单元格缩短了，拖好以后就正常了，表格是自适应的

**Comment by Barrior** [comment]
@Maxatom 你给站位元素加上宽度试试，用 `cloneStyle `，这样或许就可以防止表格自适应了
