### ISSUE TITLE
当页面的高度超过一屏时，拖拽的元素不跟随鼠标啦

### ISSUE THREAD

**Issue by gaowei-space** [Barrior/DDSort#4]
当页面的高度超过一屏时，拖拽的元素不跟随鼠标啦，我把position改为了absolute没问题啦，不过还是来给你做个反馈，插件很棒，真好符合我的需求，thanks.

**Comment by Barrior** [comment]
@china-shevy 
你可以用在线编辑器 CodePen 或者 JSFiddle 写个例子吗，方便了解你说的问题，解决问题。

**Comment by Barrior** [comment]
修复问题了 @china-shevy
