### ISSUE TITLE
Top settging error

### ISSUE THREAD

**Issue by nkuglien** [Barrior/DDSort#5]
When you have a scrolling the top position fail.
I found the error:
 $this.css({
	 left: left,
	top: top 
}
I changed it with
 $this.css({
			left: left,
			top: top - document.body.scrollTop
}

**Comment by Barrior** [comment]
@nkuglien 
Can you create an example on CodePen or other online editers?
Well, maybe I know your problem and fix it.

**Comment by Barrior** [comment]
Has been fix. @nkuglien
