### ISSUE TITLE
水平多个同级标签，左右拖动会有闪屏的bug

### ISSUE THREAD

**Issue by mqy1023** [Barrior/DDSort#6]
水平多个同级标签，左右拖动会有闪屏的bug

**Comment by Barrior** [comment]
@mqy1023 
你可以用在线编辑器 CodePen 或者 JSFiddle 写个例子吗，方便了解你说的问题。

**Comment by siminx** [comment]
@mqy1023 你的问题这个PR可以解决。
https://github.com/Barrior/DDSort/pull/12
