### ISSUE TITLE
在bootstrap的modal中使用，拖动元素定位有问题

### ISSUE THREAD

**Issue by lixiaominggit** [Barrior/DDSort#7]

**Comment by lixiaominggit** [comment]
![image](https://cloud.githubusercontent.com/assets/5425397/25417569/8a812e7c-2a77-11e7-9bd3-850e28b0d07e.png)

**Comment by Barrior** [comment]
@lixiaominggit 是有这个问题，有空的时候得改一下，谢谢反馈

**Comment by Barrior** [comment]
已有修复方案，请参考 [http://barrior.github.io/DDSort/demo_bootstrap.html](http://barrior.github.io/DDSort/demo_bootstrap.html)
