### ISSUE TITLE
当wrap容器所在的页面有滚动的时候，拖动的定位会有问题

### ISSUE THREAD

**Issue by ylb1992** [Barrior/DDSort#8]
具体复现步骤，在demo.html的wrap容器上添加`margin-top: 1000px;`<br>
目测代码是由于定位的时候，取的是document为基准点，没有考虑到`document`滚动的情况<br>
建议在计算left和top的时候，算上`scrollLeft`和`scrollTop`

**Comment by Barrior** [comment]
有空修复一下，谢谢提 bug！

**Comment by Barrior** [comment]
修复了 @ylb1992
